from flask import Flask, render_template, request, jsonify
import subprocess
import sys
import os
import json

app = Flask(__name__)
EXE_NAME = "engine.exe" if sys.platform == "win32" else "./engine"

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/run_sweep', methods=['POST'])
def run_sweep():
    # 1. Run C Engine
    process = subprocess.run([EXE_NAME], text=True, capture_output=True)
    output = process.stdout.strip()
    
    parts = output.split('|')
    processed = parts[0].split(':')[1] if len(parts) > 0 else "0"
    frauds_count = parts[1].split(':')[1] if len(parts) > 1 else "0"
    
    fraud_list = []
    safe_list = []
    
    # 2. Read the new Comprehensive Vector Log generated by C
    if os.path.exists("sweep_results.log"):
        with open("sweep_results.log", "r") as f:
            for line in f:
                details = line.strip().split('|')
                if len(details) >= 6:
                    obj = {
                        "txn_id": details[0],
                        "amount": f"₹{details[1]}",
                        "time": details[2],
                        "category": details[3],
                        "reason": details[5] # The new XAI Reason String!
                    }
                    if details[4] == "FRAUD":
                        fraud_list.append(obj)
                    else:
                        safe_list.append(obj)
    
    return jsonify({
        "processed": processed,
        "frauds_count": frauds_count,
        "safe_count": str(len(safe_list)),
        "alerts": fraud_list[:100],  
        "safe": safe_list[:100]      
    })

@app.route('/api/tree', methods=['GET'])
def get_tree():
    try:
        process = subprocess.run([EXE_NAME, "--tree"], text=True, capture_output=True)
        return jsonify(json.loads(process.stdout.strip()))
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)